"""add negotiation outcome model

Revision ID: 5a1b3c2d4e8f
Revises: 2a8f9c1d0b3e
Create Date: 2023-12-06 10:00:00.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a1b3c2d4e8f'
down_revision = '2a8f9c1d0b3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negotiation_outcomes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('original_clause_hash', sa.String(), nullable=False),
    sa.Column('counter_offer_hash', sa.String(), nullable=False),
    sa.Column('outcome', sa.Enum('accepted', 'rejected', name='negotiationoutcomeenum'), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('negotiation_duration_days', sa.Integer(), nullable=True),
    sa.Column('contract_value', sa.Integer(), nullable=True),
    sa.Column('counterparty_industry', sa.String(), nullable=True),
    sa.Column('clause_category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_outcomes_clause_category'), 'negotiation_outcomes', ['clause_category'], unique=False)
    op.create_index(op.f('ix_negotiation_outcomes_counter_offer_hash'), 'negotiation_outcomes', ['counter_offer_hash'], unique=False)
    op.create_index(op.f('ix_negotiation_outcomes_original_clause_hash'), 'negotiation_outcomes', ['original_clause_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_negotiation_outcomes_original_clause_hash'), table_name='negotiation_outcomes')
    op.drop_index(op.f('ix_negotiation_outcomes_counter_offer_hash'), table_name='negotiation_outcomes')
    op.drop_index(op.f('ix_negotiation_outcomes_clause_category'), table_name='negotiation_outcomes')
    op.drop_table('negotiation_outcomes')
    op.execute("DROP TYPE negotiationoutcomeenum;")
    # ### end Alembic commands ###