"""Add post-signature models

Revision ID: e8a7c5d6b9f0
Revises: c9d8e7f6a5b4
Create Date: 2023-11-01 11:30:45.123456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8a7c5d6b9f0'
down_revision = 'c9d8e7f6a5b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('contract_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('milestone_type', sa.Enum('EFFECTIVE_DATE', 'EXPIRATION_DATE', 'AUTO_RENEWAL_DATE', 'RENEWAL_NOTICE_DEADLINE', 'TERMINATION_NOTICE_DEADLINE', name='milestonetype'), nullable=False),
    sa.Column('milestone_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_ai', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_milestones_id'), 'contract_milestones', ['id'], unique=False)
    op.create_table('tracked_obligations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('obligation_text', sa.Text(), nullable=False),
    sa.Column('responsible_party', sa.Enum('OUR_COMPANY', 'COUNTERPARTY', name='responsibleparty'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', name='obligationstatus'), nullable=False),
    sa.Column('created_by_ai', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_obligations_id'), 'tracked_obligations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracked_obligations_id'), table_name='tracked_obligations')
    op.drop_table('tracked_obligations')
    op.drop_index(op.f('ix_contract_milestones_id'), table_name='contract_milestones')
    op.drop_table('contract_milestones')
    op.execute('DROP TYPE obligationstatus;')
    op.execute('DROP TYPE responsibleparty;')
    op.execute('DROP TYPE milestonetype;')
    # ### end Alembic commands ###