services:
  db:
    image: postgres:15-alpine
    container_name: lexi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lexiuser
      - POSTGRES_PASSWORD=lexipass
      - POSTGRES_DB=lexicontract_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lexiuser -d lexicontract_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: lexi_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lexi_frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data: